// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Teste_Pratico_API_TPC.Models;

[Table("tb_tarefa")]
public partial class TbTarefa
{
    [Key]
    [Column("id_tarefa")]
    public int IdTarefa { get; set; }

    [Required]
    [Column("ta_titulo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TaTitulo { get; set; }

    [Required]
    [Column("ta_descricao")]
    [StringLength(200)]
    [Unicode(false)]
    public string TaDescricao { get; set; }

    [Required]
    [Column("ta_status")]
    [StringLength(50)]
    [Unicode(false)]
    public string TaStatus { get; set; }

    [Column("fk_usuario")]
    public int FkUsuario { get; set; }

    [ForeignKey("FkUsuario")]
    [InverseProperty("TbTarefas")]
    public virtual TbUsuario FkUsuarioNavigation { get; set; }
}