// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Teste_Pratico_API_TPC.Models;

[Table("tb_usuario")]
public partial class TbUsuario
{
    [Key]
    [Column("id_usuario")]
    public int IdUsuario { get; set; }

    [Required]
    [Column("us_nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsNome { get; set; }

    [Required]
    [Column("us_email")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsEmail { get; set; }

    [Required]
    [Column("us_senha")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsSenha { get; set; }

    [InverseProperty("FkUsuarioNavigation")]
    public virtual ICollection<TbTarefa> TbTarefas { get; set; } = new List<TbTarefa>();
}