// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Teste_Pratico_API_TPC.Models;

namespace Teste_Pratico_API_TPC.Data;

public partial class BancoTPCContext : DbContext
{
    public BancoTPCContext(DbContextOptions<BancoTPCContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TbTarefa> TbTarefas { get; set; }

    public virtual DbSet<TbUsuario> TbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TbTarefa>(entity =>
        {
            entity.HasOne(d => d.FkUsuarioNavigation).WithMany(p => p.TbTarefas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__tb_tarefa__fk_us__45F365D3");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}